import { EventItem } from "@/types/events";

/**
 * Google Calendar & iCalendar Integration Utilities
 */

/**
 * Formats a Date object or date + time string into Google Calendar template format (YYYYMMDDTHHmmSS)
 */
export function formatGoogleCalendarDate(dateStr: string, timeStr: string, durationMinutes = 120): {
  start: string;
  end: string;
} {
  try {
    const [year, month, day] = dateStr.split("-").map(Number);
    const [hours, minutes] = (timeStr || "10:00").split(":").map(Number);

    const startDate = new Date(year, month - 1, day, hours, minutes, 0);
    const endDate = new Date(startDate.getTime() + durationMinutes * 60 * 1000);

    const pad = (n: number) => String(n).padStart(2, "0");

    const format = (d: Date) =>
      `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}T${pad(d.getHours())}${pad(
        d.getMinutes()
      )}00`;

    return {
      start: format(startDate),
      end: format(endDate),
    };
  } catch {
    const fallbackDate = dateStr.replace(/-/g, "");
    return {
      start: `${fallbackDate}T090000`,
      end: `${fallbackDate}T110000`,
    };
  }
}

/**
 * Builds rich, contextual event description for Google Calendar
 */
export function buildGoogleCalendarDetails(event: EventItem): string {
  const lines: string[] = [];

  lines.push(`✦ OP AI Scheduled Event: ${event.title}`);
  if (event.type) lines.push(`• Occasion / Category: ${event.type}`);
  if (event.priority) lines.push(`• Priority: ${event.priority}`);

  if (event.plannedOutfit?.topItemName) {
    lines.push("");
    lines.push("👔 Recommended Outfit:");
    lines.push(`• Top: ${event.plannedOutfit.topItemName}`);
    if (event.plannedOutfit.bottomItemName) lines.push(`• Bottom: ${event.plannedOutfit.bottomItemName}`);
    if (event.plannedOutfit.shoesItemName) lines.push(`• Shoes: ${event.plannedOutfit.shoesItemName}`);
  }

  if (event.selectedTransitMode) {
    lines.push("");
    lines.push(`🚆 Transit Plan: ${event.selectedTransitMode}`);
    if (event.originLocation) lines.push(`• Origin: ${event.originLocation}`);
  }

  if (event.notes) {
    lines.push("");
    lines.push(`📝 Notes: ${event.notes}`);
  }

  lines.push("");
  lines.push("Generated by OmniPresence (OP AI) Personal Intelligence");

  return lines.join("\n");
}

/**
 * Generates direct Google Calendar Web Intent URL
 */
export function getGoogleCalendarUrl(event: EventItem, durationMinutes = 120): string {
  const { start, end } = formatGoogleCalendarDate(event.date, event.time, durationMinutes);
  const title = encodeURIComponent(event.title);
  const location = encodeURIComponent(event.location || "");
  const details = encodeURIComponent(buildGoogleCalendarDetails(event));

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${start}/${end}&details=${details}&location=${location}`;
}

/**
 * Generates standard .ICS content for Apple Calendar, Outlook, and Google Calendar
 */
export function generateIcsContent(event: EventItem, durationMinutes = 120): string {
  const { start, end } = formatGoogleCalendarDate(event.date, event.time, durationMinutes);
  const description = buildGoogleCalendarDetails(event).replace(/\n/g, "\\n");

  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//OmniPresence//OP AI Calendar//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "BEGIN:VEVENT",
    `UID:op-event-${event.id}@omnipresence.ai`,
    `DTSTAMP:${start}Z`,
    `DTSTART:${start}`,
    `DTEND:${end}`,
    `SUMMARY:${event.title}`,
    `DESCRIPTION:${description}`,
    `LOCATION:${event.location || ""}`,
    "STATUS:CONFIRMED",
    "END:VEVENT",
    "END:VCALENDAR",
  ].join("\r\n");
}

/**
 * Triggers download of .ICS file in browser
 */
export function downloadIcsFile(event: EventItem): void {
  const icsData = generateIcsContent(event);
  const blob = new Blob([icsData], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", `${event.title.toLowerCase().replace(/[^a-z0-9]/gi, "_")}.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
