import { WardrobeItem, WearEvent } from "@/types/wardrobe";
import { Outfit } from "@/types/outfit";
import { UserProfile } from "@/types/user";

export const INITIAL_USER: UserProfile = {
  id: "user_alex_mercer",
  name: "Alex Mercer",
  email: "alex.mercer@omnipresence.ai",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
  bio: "Product Architect & Design Strategist. Passionate about minimalist aesthetics and functional intelligence.",
  stylePreferences: ["Smart Casual", "Minimal", "Casual"],
  colorPreferences: ["Black", "White", "Navy", "Beige", "Grey"],
  occasionPreferences: ["Office", "Meeting", "Everyday", "Dinner", "Date"],
  fitPreferences: ["Slim", "Tailored", "Regular"],
  sizes: {
    tops: "M",
    bottoms: "32",
    shoes: "10.5 US",
    outerwear: "40R",
  },
  preferredBrands: ["Acne Studios", "Theory", "Uniqlo U", "Common Projects", "Cos"],
  notificationSettings: {
    dailyOutfitSuggestions: true,
    wearBalancingAlerts: true,
    weatherUpdates: true,
    eventReminders: true,
  },
  connectedServices: {
    weather: true,
    calendar: false,
    financialSync: false,
  },
  theme: "system",
  onboarded: true,
  createdAt: "2026-08-01T09:00:00.000Z",
  updatedAt: "2026-09-01T10:00:00.000Z",
};

export const INITIAL_WARDROBE_ITEMS: WardrobeItem[] = [
  {
    id: "item_black_oxford",
    userId: "user_alex_mercer",
    name: "Tailored Black Oxford Shirt",
    category: "Tops",
    subcategory: "Button-Up Shirt",
    color: "Black",
    secondaryColors: ["Charcoal"],
    brand: "Theory",
    size: "M",
    fit: "Tailored",
    material: "100% Egyptian Cotton",
    season: ["Spring", "Autumn", "Winter", "All-Season"],
    occasion: ["Office", "Meeting", "Dinner", "Date"],
    imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80",
    wearCount: 8,
    lastWorn: "2026-08-28T14:30:00.000Z",
    favorite: true,
    notes: "Crisp structured collar. Ideal for executive presentations and sleek dinners.",
    createdAt: "2026-08-05T10:00:00.000Z",
    updatedAt: "2026-08-28T14:30:00.000Z",
  },
  {
    id: "item_white_tee",
    userId: "user_alex_mercer",
    name: "Heavyweight White Supima Tee",
    category: "Tops",
    subcategory: "T-Shirt",
    color: "White",
    brand: "Cos",
    size: "M",
    fit: "Regular",
    material: "Supima Cotton (240 GSM)",
    season: ["Spring", "Summer", "All-Season"],
    occasion: ["Everyday", "Weekend Casual", "Casual", "College"],
    imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80",
    wearCount: 14,
    lastWorn: "2026-08-31T09:15:00.000Z",
    favorite: true,
    notes: "Versatile base layer. Holds structure cleanly without transparency.",
    createdAt: "2026-08-02T10:00:00.000Z",
    updatedAt: "2026-08-31T09:15:00.000Z",
  },
  {
    id: "item_navy_knit",
    userId: "user_alex_mercer",
    name: "Fine Gauge Navy Merino Crewneck",
    category: "Tops",
    subcategory: "Knitwear",
    color: "Navy",
    secondaryColors: ["Blue"],
    brand: "Uniqlo U",
    size: "M",
    fit: "Slim",
    material: "100% Extra Fine Merino",
    season: ["Autumn", "Winter", "Spring"],
    occasion: ["Office", "Meeting", "Everyday", "Travel"],
    imageUrl: "https://images.unsplash.com/photo-1614975058789-41316d0e2e9c?w=600&auto=format&fit=crop&q=80",
    wearCount: 5,
    lastWorn: "2026-08-20T11:00:00.000Z",
    favorite: false,
    notes: "Soft breathable wool. Breathable for air-conditioned studios.",
    createdAt: "2026-08-08T10:00:00.000Z",
    updatedAt: "2026-08-20T11:00:00.000Z",
  },
  {
    id: "item_sage_overshirt",
    userId: "user_alex_mercer",
    name: "Sage Green Linen Utility Overshirt",
    category: "Tops",
    subcategory: "Overshirt",
    color: "Olive",
    secondaryColors: ["Beige"],
    brand: "Acne Studios",
    size: "L",
    fit: "Relaxed",
    material: "Linen-Tencel Blend",
    season: ["Spring", "Summer", "Autumn"],
    occasion: ["Casual", "Weekend Casual", "Travel", "Date"],
    imageUrl: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80",
    wearCount: 3,
    lastWorn: "2026-08-25T16:00:00.000Z",
    favorite: true,
    notes: "Dual chest pockets. Works unbuttoned over a white tee.",
    createdAt: "2026-08-12T10:00:00.000Z",
    updatedAt: "2026-08-25T16:00:00.000Z",
  },
  {
    id: "item_beige_chinos",
    userId: "user_alex_mercer",
    name: "Pleated Relaxed Beige Chinos",
    category: "Bottoms",
    subcategory: "Chinos",
    color: "Beige",
    secondaryColors: ["Tan"],
    brand: "Cos",
    size: "32",
    fit: "Relaxed",
    material: "Cotton Twill with 2% Elastane",
    season: ["Spring", "Summer", "Autumn", "All-Season"],
    occasion: ["Office", "Meeting", "Weekend Casual", "Everyday"],
    imageUrl: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&auto=format&fit=crop&q=80",
    wearCount: 11,
    lastWorn: "2026-08-29T10:00:00.000Z",
    favorite: true,
    notes: "Slight taper at the ankle. Great pairing with minimalist sneakers.",
    createdAt: "2026-08-04T10:00:00.000Z",
    updatedAt: "2026-08-29T10:00:00.000Z",
  },
  {
    id: "item_dark_jeans",
    userId: "user_alex_mercer",
    name: "Dark Indigo Selvedge Raw Jeans",
    category: "Bottoms",
    subcategory: "Jeans",
    color: "Navy",
    secondaryColors: ["Blue"],
    brand: "A.P.C.",
    size: "32",
    fit: "Slim",
    material: "13.5oz Japanese Selvedge Denim",
    season: ["All-Season", "Autumn", "Winter"],
    occasion: ["Casual", "Date", "Everyday", "Weekend Casual"],
    imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop&q=80",
    wearCount: 16,
    lastWorn: "2026-08-30T19:00:00.000Z",
    favorite: true,
    notes: "Deep uniform indigo. Clean enough to dress up with a blazer.",
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-08-30T19:00:00.000Z",
  },
  {
    id: "item_charcoal_trousers",
    userId: "user_alex_mercer",
    name: "Charcoal Melange Wool Trousers",
    category: "Bottoms",
    subcategory: "Dress Pants",
    color: "Grey",
    secondaryColors: ["Black"],
    brand: "Theory",
    size: "32",
    fit: "Tailored",
    material: "Super 120s Italian Wool",
    season: ["Autumn", "Winter", "Spring"],
    occasion: ["Office", "Meeting", "Formal Event", "Dinner"],
    imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80",
    wearCount: 4,
    lastWorn: "2026-08-15T09:00:00.000Z",
    favorite: false,
    notes: "Sharp pressed crease. Formal business meetings.",
    createdAt: "2026-08-06T10:00:00.000Z",
    updatedAt: "2026-08-15T09:00:00.000Z",
  },
  {
    id: "item_white_sneakers",
    userId: "user_alex_mercer",
    name: "Minimalist Achilles White Sneakers",
    category: "Shoes",
    subcategory: "Sneakers",
    color: "White",
    brand: "Common Projects",
    size: "10.5 US",
    fit: "Regular",
    material: "Nappa Calfskin Leather",
    season: ["Spring", "Summer", "Autumn", "All-Season"],
    occasion: ["Everyday", "Office", "Weekend Casual", "Travel", "Casual"],
    imageUrl: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&auto=format&fit=crop&q=80",
    wearCount: 22,
    lastWorn: "2026-09-01T08:30:00.000Z",
    favorite: true,
    notes: "The everyday uniform shoe. Sleek profile with gold serial stamp.",
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-09-01T08:30:00.000Z",
  },
  {
    id: "item_chelsea_boots",
    userId: "user_alex_mercer",
    name: "Matte Black Leather Chelsea Boots",
    category: "Shoes",
    subcategory: "Boots",
    color: "Black",
    brand: "Saint Laurent",
    size: "10.5 US",
    fit: "Slim",
    material: "Full Grain Box Calfskin",
    season: ["Autumn", "Winter", "Spring"],
    occasion: ["Date", "Dinner", "Formal Event", "Meeting"],
    imageUrl: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=600&auto=format&fit=crop&q=80",
    wearCount: 6,
    lastWorn: "2026-08-22T20:00:00.000Z",
    favorite: true,
    notes: "Streamlined silhouette with durable storm welt.",
    createdAt: "2026-08-03T10:00:00.000Z",
    updatedAt: "2026-08-22T20:00:00.000Z",
  },
  {
    id: "item_brown_loafers",
    userId: "user_alex_mercer",
    name: "Espresso Suede Penny Loafers",
    category: "Shoes",
    subcategory: "Loafers",
    color: "Brown",
    secondaryColors: ["Tan"],
    brand: "Crockett & Jones",
    size: "10.5 US",
    fit: "Tailored",
    material: "Hydro Suede Calfskin",
    season: ["Spring", "Summer", "Autumn"],
    occasion: ["Office", "Meeting", "Dinner", "Date"],
    imageUrl: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop&q=80",
    wearCount: 7,
    lastWorn: "2026-08-26T12:00:00.000Z",
    favorite: false,
    notes: "Casual sophistication with unlined flexible sole.",
    createdAt: "2026-08-07T10:00:00.000Z",
    updatedAt: "2026-08-26T12:00:00.000Z",
  },
  {
    id: "item_bomber_jacket",
    userId: "user_alex_mercer",
    name: "Minimalist Matte Bomber Jacket",
    category: "Outerwear",
    subcategory: "Bomber",
    color: "Black",
    brand: "Acne Studios",
    size: "40R",
    fit: "Regular",
    material: "Water-Resistant Technical Twill",
    season: ["Spring", "Autumn", "Winter"],
    occasion: ["Casual", "Everyday", "Travel", "Weekend Casual"],
    imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80",
    wearCount: 9,
    lastWorn: "2026-08-27T18:00:00.000Z",
    favorite: false,
    notes: "Clean collarless neckline and subtle silver hardware.",
    createdAt: "2026-08-09T10:00:00.000Z",
    updatedAt: "2026-08-27T18:00:00.000Z",
  },
  {
    id: "item_wool_overcoat",
    userId: "user_alex_mercer",
    name: "Double-Faced Charcoal Wool Overcoat",
    category: "Outerwear",
    subcategory: "Coat",
    color: "Grey",
    secondaryColors: ["Black"],
    brand: "Cos Atelier",
    size: "40R",
    fit: "Tailored",
    material: "90% Cashmere-Wool Blend",
    season: ["Autumn", "Winter"],
    occasion: ["Formal Event", "Office", "Meeting", "Dinner"],
    imageUrl: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&auto=format&fit=crop&q=80",
    wearCount: 2,
    lastWorn: "2026-08-10T08:00:00.000Z",
    favorite: true,
    notes: "Sculptural silhouette that anchors formal winter layers.",
    createdAt: "2026-08-10T10:00:00.000Z",
    updatedAt: "2026-08-10T10:00:00.000Z",
  },
  {
    id: "item_leather_belt",
    userId: "user_alex_mercer",
    name: "Architectural Matte Leather Belt",
    category: "Accessories",
    subcategory: "Belt",
    color: "Black",
    brand: "Lemaire",
    size: "32",
    material: "Bridle Leather & Brushed Nickel",
    season: ["All-Season"],
    occasion: ["Office", "Meeting", "Dinner", "Everyday"],
    imageUrl: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600&auto=format&fit=crop&q=80",
    wearCount: 18,
    lastWorn: "2026-08-30T10:00:00.000Z",
    favorite: false,
    notes: "Seamless minimal buckle.",
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-08-30T10:00:00.000Z",
  },
  {
    id: "item_silver_watch",
    userId: "user_alex_mercer",
    name: "Bauhaus Minimal Silver Chronograph",
    category: "Accessories",
    subcategory: "Watch",
    color: "White",
    secondaryColors: ["Grey"],
    brand: "Junghans",
    material: "Stainless Steel & Sapphire Glass",
    season: ["All-Season"],
    occasion: ["Office", "Meeting", "Formal Event", "Dinner", "Date"],
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
    wearCount: 25,
    lastWorn: "2026-09-01T08:00:00.000Z",
    favorite: true,
    notes: "Timeless German engineering with clean typographic dial.",
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-09-01T08:00:00.000Z",
  }
];

export const INITIAL_WEAR_EVENTS: WearEvent[] = [
  {
    id: "wear_001",
    wardrobeItemId: "item_white_sneakers",
    date: "2026-09-01",
    occasion: "Office",
    notes: "Worn with casual Friday work outfit.",
    createdAt: "2026-09-01T08:30:00.000Z",
  },
  {
    id: "wear_002",
    wardrobeItemId: "item_white_tee",
    date: "2026-08-31",
    occasion: "Everyday",
    notes: "Worn during weekend brainstorming session.",
    createdAt: "2026-08-31T09:15:00.000Z",
  },
  {
    id: "wear_003",
    wardrobeItemId: "item_dark_jeans",
    date: "2026-08-30",
    occasion: "Date",
    notes: "Dinner at Bistro Moderne.",
    createdAt: "2026-08-30T19:00:00.000Z",
  },
  {
    id: "wear_004",
    wardrobeItemId: "item_beige_chinos",
    date: "2026-08-29",
    occasion: "Office",
    notes: "Product review meeting.",
    createdAt: "2026-08-29T10:00:00.000Z",
  },
  {
    id: "wear_005",
    wardrobeItemId: "item_black_oxford",
    date: "2026-08-28",
    occasion: "Meeting",
    notes: "Investor update call.",
    createdAt: "2026-08-28T14:30:00.000Z",
  },
  {
    id: "wear_006",
    wardrobeItemId: "item_brown_loafers",
    date: "2026-08-26",
    occasion: "Office",
    notes: "Worn with beige chinos.",
    createdAt: "2026-08-26T12:00:00.000Z",
  },
];

export const INITIAL_OUTFITS: Outfit[] = [
  {
    id: "outfit_executive_briefing",
    userId: "user_alex_mercer",
    name: "Executive Briefing & Strategy",
    items: [
      "item_black_oxford",
      "item_beige_chinos",
      "item_brown_loafers",
      "item_silver_watch"
    ],
    occasion: "Meeting",
    date: "2026-09-03",
    notes: "High-contrast smart-casual balance with polished suede loafers.",
    favorite: true,
    wearCount: 3,
    lastWorn: "2026-08-26T12:00:00.000Z",
    createdAt: "2026-08-10T10:00:00.000Z",
    updatedAt: "2026-08-26T12:00:00.000Z",
  },
  {
    id: "outfit_minimalist_weekend",
    userId: "user_alex_mercer",
    name: "Weekend Studio & Gallery Walk",
    items: [
      "item_white_tee",
      "item_sage_overshirt",
      "item_dark_jeans",
      "item_white_sneakers"
    ],
    occasion: "Weekend Casual",
    date: "2026-09-06",
    notes: "Layered sage overshirt over heavyweight white tee with clean sneakers.",
    favorite: true,
    wearCount: 4,
    lastWorn: "2026-08-25T16:00:00.000Z",
    createdAt: "2026-08-12T10:00:00.000Z",
    updatedAt: "2026-08-25T16:00:00.000Z",
  },
  {
    id: "outfit_evening_dinner",
    userId: "user_alex_mercer",
    name: "Evening Culinary & Drinks",
    items: [
      "item_black_oxford",
      "item_charcoal_trousers",
      "item_chelsea_boots",
      "item_leather_belt"
    ],
    occasion: "Dinner",
    date: null,
    notes: "Monochrome architectural evening look with Chelsea boots.",
    favorite: false,
    wearCount: 2,
    lastWorn: "2026-08-22T20:00:00.000Z",
    createdAt: "2026-08-15T10:00:00.000Z",
    updatedAt: "2026-08-22T20:00:00.000Z",
  }
];

export const INITIAL_EVENTS: any[] = [
  {
    id: "event_college_pres",
    userId: "user_alex_mercer",
    title: "College Presentation",
    date: new Date(Date.now() + 86400000).toISOString().split("T")[0], // Tomorrow
    time: "10:00",
    location: "Main Campus Auditorium",
    originLocation: "Tambaram",
    type: "Presentation",
    priority: "High",
    notes: "Final thesis defense on Artificial Intelligence in Architecture.",
    dressCode: "Business Formal",
    plannedOutfit: {
      topItemId: "item_black_oxford",
      topItemName: "Tailored Black Oxford Shirt",
      bottomItemId: "item_charcoal_trousers",
      bottomItemName: "Italian Wool Charcoal Trousers",
      shoesItemId: "item_chelsea_boots",
      shoesItemName: "Black Leather Chelsea Boots",
      accessoryNames: ["Minimalist Silver Watch"],
    },
    selectedTransitMode: "Metro",
    completedChecklist: ["event_confirmed", "outfit_selected", "footwear_selected", "weather_checked"],
    createdAt: "2026-08-20T10:00:00.000Z",
    updatedAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "event_wedding_rec",
    userId: "user_alex_mercer",
    title: "Wedding Reception",
    date: new Date(Date.now() + 172800000).toISOString().split("T")[0], // In 2 days
    time: "19:00",
    location: "Nungambakkam Grand Hall",
    originLocation: "Tambaram",
    type: "Wedding",
    priority: "High",
    notes: "Reception evening celebration with friends and family.",
    dressCode: "Festive Formal",
    plannedOutfit: {
      topItemId: "item_navy_knit",
      topItemName: "Fine Gauge Navy Merino Crewneck",
      bottomItemId: "item_charcoal_trousers",
      bottomItemName: "Italian Wool Charcoal Trousers",
      shoesItemId: "item_brown_loafers",
      shoesItemName: "Burnished Brown Suede Loafers",
      accessoryNames: ["Silk Pocket Square", "Leather Belt"],
    },
    selectedTransitMode: "Train",
    completedChecklist: [
      "event_confirmed",
      "outfit_selected",
      "footwear_selected",
      "transportation_planned",
      "weather_checked",
      "reminders_created",
      "accessories_prepared",
    ],
    createdAt: "2026-08-22T10:00:00.000Z",
    updatedAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "event_tcs_interview",
    userId: "user_alex_mercer",
    title: "Interview at TCS",
    date: new Date(Date.now() + 345600000).toISOString().split("T")[0], // In 4 days
    time: "10:00",
    location: "TCS Siruseri Campus",
    originLocation: "Tambaram",
    type: "Job Interview",
    priority: "High",
    notes: "Technical architecture evaluation and leadership interview.",
    dressCode: "Strict Business Formal",
    selectedTransitMode: "Train",
    completedChecklist: ["event_confirmed", "weather_checked"],
    createdAt: "2026-08-25T10:00:00.000Z",
    updatedAt: "2026-09-01T10:00:00.000Z",
  },
];

export const INITIAL_REMINDERS: any[] = [
  {
    id: "rem_1",
    userId: "user_alex_mercer",
    eventId: "event_wedding_rec",
    eventTitle: "Wedding Reception",
    title: "Start getting ready & grooming",
    type: "grooming",
    date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
    time: "17:00",
    isCompleted: false,
    priority: "High",
    autoGenerated: true,
    createdAt: "2026-08-28T10:00:00.000Z",
    updatedAt: "2026-08-28T10:00:00.000Z",
  },
  {
    id: "rem_2",
    userId: "user_alex_mercer",
    eventId: "event_wedding_rec",
    eventTitle: "Wedding Reception",
    title: "Iron festive outfit & shine leather loafers",
    type: "iron",
    date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
    time: "17:30",
    isCompleted: false,
    priority: "Medium",
    autoGenerated: true,
    createdAt: "2026-08-28T10:00:00.000Z",
    updatedAt: "2026-08-28T10:00:00.000Z",
  },
  {
    id: "rem_3",
    userId: "user_alex_mercer",
    eventId: "event_wedding_rec",
    eventTitle: "Wedding Reception",
    title: "Get dressed in Navy Festive outfit",
    type: "outfit",
    date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
    time: "18:00",
    isCompleted: false,
    priority: "High",
    autoGenerated: true,
    createdAt: "2026-08-28T10:00:00.000Z",
    updatedAt: "2026-08-28T10:00:00.000Z",
  },
  {
    id: "rem_4",
    userId: "user_alex_mercer",
    eventId: "event_wedding_rec",
    eventTitle: "Wedding Reception",
    title: "Leave for Nungambakkam via Suburban EMU Train",
    type: "departure",
    date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
    time: "18:15",
    isCompleted: false,
    priority: "High",
    autoGenerated: true,
    createdAt: "2026-08-28T10:00:00.000Z",
    updatedAt: "2026-08-28T10:00:00.000Z",
  },
];

export const INITIAL_FINANCIAL_PLAN: any = {
  userId: "user_alex_mercer",
  monthlyBudget: 0,
  monthlyFashionBudget: 0,
  clothingBudget: 0,
  shoppingLimit: 0,
  savingsGoal: 0,
  spentThisMonth: 0,
  currency: "₹",
  transactions: [],
  updatedAt: new Date().toISOString(),
};
