import { EventItem } from "@/types/events";
import { ReminderItem } from "@/types/reminders";
import { AppStorage } from "@/lib/storage";
import { EventUnderstandingEngine } from "@/lib/eventUnderstandingEngine";
import { remindersService } from "./remindersService";

export const calendarService = {
  getEvents: async (): Promise<EventItem[]> => {
    const userId = AppStorage.getActiveUserId() || "user_alex_mercer";
    return AppStorage.getEvents(userId);
  },

  getEventById: async (id: string): Promise<EventItem | null> => {
    const userId = AppStorage.getActiveUserId() || "user_alex_mercer";
    return AppStorage.getEvent(userId, id);
  },

  createEvent: async (
    eventData: Partial<EventItem>
  ): Promise<EventItem> => {
    const userId = AppStorage.getActiveUserId() || "user_alex_mercer";
    const id = `event_${Date.now()}_${Math.random().toString(36).substr(2, 4)}`;

    const newEvent: EventItem = {
      id,
      userId,
      title: eventData.title || "Untitled Event",
      date: eventData.date || new Date().toISOString().split("T")[0],
      time: eventData.time || "10:00",
      endTime: eventData.endTime,
      location: eventData.location || "Venue",
      originLocation: eventData.originLocation || "Tambaram",
      type: eventData.type || "Other",
      priority: eventData.priority || "Medium",
      notes: eventData.notes || "",
      dressCode: eventData.dressCode,
      plannedOutfit: eventData.plannedOutfit,
      selectedTransitMode: eventData.selectedTransitMode,
      completedChecklist: eventData.completedChecklist || ["event_confirmed"],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    AppStorage.saveEvent(userId, newEvent);

    // Auto-generate suggested reminders
    try {
      await calendarService.autoGenerateRemindersForEvent(newEvent);
    } catch (e) {
      console.warn("Failed to auto-generate reminders:", e);
    }

    return newEvent;
  },

  updateEvent: async (event: EventItem): Promise<EventItem> => {
    const userId = AppStorage.getActiveUserId() || "user_alex_mercer";
    AppStorage.saveEvent(userId, event);
    return event;
  },

  deleteEvent: async (id: string): Promise<boolean> => {
    const userId = AppStorage.getActiveUserId() || "user_alex_mercer";
    AppStorage.deleteEvent(userId, id);
    return true;
  },

  autoGenerateRemindersForEvent: async (event: EventItem): Promise<ReminderItem[]> => {
    const userId = AppStorage.getActiveUserId() || "user_alex_mercer";
    const inf = EventUnderstandingEngine.inferEventContext(event);

    const generated: ReminderItem[] = [];

    for (const item of inf.preparationTimeline) {
      if (!item.defaultReminder) continue;

      const [hStr, mStr] = (event.time || "10:00").split(":");
      const totalMins = (parseInt(hStr, 10) || 10) * 60 + (parseInt(mStr, 10) || 0) - item.timeBeforeMin;
      const validMins = totalMins < 0 ? totalMins + 24 * 60 : totalMins;
      const rH = Math.floor(validMins / 60) % 24;
      const rM = validMins % 60;
      const pad = (n: number) => (n < 10 ? `0${n}` : `${n}`);
      const remTime = `${pad(rH)}:${pad(rM)}`;

      const rem: ReminderItem = {
        id: `rem_${Date.now()}_${Math.random().toString(36).substr(2, 4)}`,
        userId,
        eventId: event.id,
        eventTitle: event.title,
        title: item.task,
        type: item.type,
        date: event.date,
        time: remTime,
        isCompleted: false,
        priority: event.priority,
        autoGenerated: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      AppStorage.saveReminder(userId, rem);
      generated.push(rem);
    }

    return generated;
  },
};
