import { ReminderItem } from "@/types/reminders";
import { AppStorage } from "@/lib/storage";

export const remindersService = {
  getReminders: async (): Promise<ReminderItem[]> => {
    const userId = AppStorage.getActiveUserId() || "user_alex_mercer";
    return AppStorage.getReminders(userId);
  },

  createReminder: async (
    data: Partial<ReminderItem>
  ): Promise<ReminderItem> => {
    const userId = AppStorage.getActiveUserId() || "user_alex_mercer";
    const id = `rem_${Date.now()}_${Math.random().toString(36).substr(2, 4)}`;

    const newReminder: ReminderItem = {
      id,
      userId,
      eventId: data.eventId,
      eventTitle: data.eventTitle,
      title: data.title || "Untitled Reminder",
      type: data.type || "custom",
      date: data.date || new Date().toISOString().split("T")[0],
      time: data.time || "09:00",
      isCompleted: false,
      priority: data.priority || "Medium",
      autoGenerated: data.autoGenerated || false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    AppStorage.saveReminder(userId, newReminder);
    return newReminder;
  },

  updateReminder: async (reminder: ReminderItem): Promise<ReminderItem> => {
    const userId = AppStorage.getActiveUserId() || "user_alex_mercer";
    AppStorage.saveReminder(userId, reminder);
    return reminder;
  },

  toggleComplete: async (id: string): Promise<ReminderItem | null> => {
    const userId = AppStorage.getActiveUserId() || "user_alex_mercer";
    const reminders = AppStorage.getReminders(userId);
    const item = reminders.find((r) => r.id === id);
    if (!item) return null;

    const updated: ReminderItem = {
      ...item,
      isCompleted: !item.isCompleted,
      updatedAt: new Date().toISOString(),
    };

    AppStorage.saveReminder(userId, updated);
    return updated;
  },

  deleteReminder: async (id: string): Promise<boolean> => {
    const userId = AppStorage.getActiveUserId() || "user_alex_mercer";
    AppStorage.deleteReminder(userId, id);
    return true;
  },
};
