"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { PopulatedOutfit } from "@/types/outfit";
import { outfitService } from "@/services/outfitService";
import { OutfitCard } from "@/components/outfits/OutfitCard";
import { Button } from "@/components/ui/Button";
import { Tabs } from "@/components/ui/Tabs";
import { EmptyState } from "@/components/ui/EmptyState";
import { Modal } from "@/components/ui/Modal";
import { useToast } from "@/context/ToastContext";
import { Layers, Plus, Sparkles, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";

export default function OutfitsPage() {
  const router = useRouter();
  const { success, error: toastError } = useToast();

  const [outfits, setOutfits] = useState<PopulatedOutfit[]>([]);
  const [activeTab, setActiveTab] = useState("all");
  const [deletingOutfit, setDeletingOutfit] = useState<PopulatedOutfit | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

  const loadOutfits = async () => {
    try {
      const data = await outfitService.getAllPopulatedOutfits();
      setOutfits(data);
    } catch (e) {
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadOutfits();
  }, []);

  const tabs = [
    { id: "all", label: "All Outfits", count: outfits.length },
    {
      id: "favorites",
      label: "Favorites",
      count: outfits.filter((o) => o.favorite).length,
    },
    {
      id: "office",
      label: "Office & Meeting",
      count: outfits.filter(
        (o) =>
          o.occasion.toLowerCase().includes("office") ||
          o.occasion.toLowerCase().includes("meeting")
      ).length,
    },
    {
      id: "casual",
      label: "Casual & Everyday",
      count: outfits.filter(
        (o) =>
          o.occasion.toLowerCase().includes("casual") ||
          o.occasion.toLowerCase().includes("everyday")
      ).length,
    },
  ];

  const filteredOutfits = outfits.filter((outfit) => {
    if (activeTab === "favorites") return outfit.favorite;
    if (activeTab === "office") {
      return (
        outfit.occasion.toLowerCase().includes("office") ||
        outfit.occasion.toLowerCase().includes("meeting")
      );
    }
    if (activeTab === "casual") {
      return (
        outfit.occasion.toLowerCase().includes("casual") ||
        outfit.occasion.toLowerCase().includes("everyday")
      );
    }
    return true;
  });

  const confirmDelete = async () => {
    if (!deletingOutfit) return;
    setIsDeleting(true);
    try {
      await outfitService.deleteOutfit(deletingOutfit.id);
      success("Outfit removed", `"${deletingOutfit.name}" has been deleted.`);
      setDeletingOutfit(null);
      loadOutfits();
    } catch (err: any) {
      toastError("Failed to delete outfit", err.message);
    } finally {
      setIsDeleting(false);
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl sm:text-3xl font-black text-[var(--text-primary)] tracking-tight">
              Planned Outfits & Ensembles
            </h1>
            <span className="text-xs font-bold px-2.5 py-0.5 rounded-full bg-[var(--primary-soft)] text-[var(--primary)]">
              {outfits.length} {outfits.length === 1 ? "look" : "looks"}
            </span>
          </div>
          <p className="text-xs sm:text-sm text-[var(--text-secondary)] mt-1">
            Browse, plan, and log outfits curated manually or generated by OP AI.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <Link href="/outfits/new">
            <Button
              variant="primary"
              size="md"
              leftIcon={<Plus className="w-4 h-4" />}
            >
              Plan New Outfit
            </Button>
          </Link>
        </div>
      </div>

      {/* Tabs */}
      <Tabs tabs={tabs} activeTab={activeTab} onChange={setActiveTab} />

      {/* Outfits Grid */}
      {filteredOutfits.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredOutfits.map((outfit) => (
            <OutfitCard
              key={outfit.id}
              outfit={outfit}
              onEdit={(o) => router.push(`/outfits/${o.id}`)}
              onDelete={(o) => setDeletingOutfit(o)}
              onRefresh={loadOutfits}
            />
          ))}
        </div>
      ) : (
        <EmptyState
          icon={<Layers className="w-8 h-8 text-[var(--primary)]" />}
          title="No planned outfits found"
          description="Compose an outfit from your wardrobe or ask OP AI to curate a look for any occasion."
          actionLabel="+ Plan an Outfit"
          onAction={() => router.push("/outfits/new")}
        />
      )}

      {/* Delete Confirmation Modal */}
      <Modal
        isOpen={Boolean(deletingOutfit)}
        onClose={() => setDeletingOutfit(null)}
        title="Delete Planned Outfit?"
        description="This will remove this outfit composition. Your individual wardrobe items will not be deleted."
        maxWidth="sm"
      >
        <div className="space-y-4 pt-2">
          {deletingOutfit && (
            <div className="p-3 rounded-2xl bg-[var(--surface-soft)] border border-[var(--border)]">
              <p className="text-sm font-bold text-[var(--text-primary)]">
                {deletingOutfit.name}
              </p>
              <p className="text-xs text-[var(--text-muted)] mt-0.5">
                {deletingOutfit.items.length} items • {deletingOutfit.occasion}
              </p>
            </div>
          )}
          <div className="flex items-center justify-end gap-3 pt-2">
            <Button
              variant="ghost"
              size="md"
              onClick={() => setDeletingOutfit(null)}
              disabled={isDeleting}
            >
              Cancel
            </Button>
            <Button
              variant="danger"
              size="md"
              onClick={confirmDelete}
              isLoading={isDeleting}
              leftIcon={<Trash2 className="w-4 h-4" />}
            >
              Delete Outfit
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
