export type ReminderType =
  | "outfit"
  | "iron"
  | "accessories"
  | "grooming"
  | "pack"
  | "weather"
  | "transit"
  | "departure"
  | "shopping"
  | "custom";

export interface ReminderItem {
  id: string;
  userId: string;
  eventId?: string;
  eventTitle?: string;
  title: string;
  type: ReminderType;
  date: string; // YYYY-MM-DD
  time: string; // HH:MM
  isCompleted: boolean;
  priority: "High" | "Medium" | "Low";
  autoGenerated?: boolean;
  createdAt: string;
  updatedAt: string;
}
