import {
  MarketplaceProduct,
  FashionParsedQuery,
  MarketplaceSearchFilters,
  MarketplaceProviderName,
  MarketplaceProviderStatus,
  MarketplaceProviderTestResult,
  MarketplaceProviderHealthStatus,
} from "@/types/marketplace";
import { IMarketplaceProvider } from "./MarketplaceProvider";

export const LOCAL_MARKETPLACE_CATALOG: MarketplaceProduct[] = [
  // =========================================================================
  // MEN'S COLLECTION
  // =========================================================================

  // --- MEN'S TOPS ---
  {
    id: "loc_men_top_01",
    provider: "Local",
    providerProductId: "dev_men_1001",
    title: "Classic White Linen Button-Down Shirt",
    description: "Breathable pure French linen shirt with a tailored spread collar and relaxed natural drape.",
    brand: "Linen & Co",
    store: "Myntra",
    merchant: "Myntra",
    imageUrl: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.myntra.com/shirts/linen-classic-white",
    price: 1899,
    originalPrice: 2499,
    currency: "INR",
    discountPercent: 24,
    discountPercentage: 24,
    priceStatus: "development",
    rating: 4.7,
    reviewCount: 184,
    availability: "in_stock",
    category: "Tops",
    subcategory: "Shirts",
    colors: ["White", "Cream"],
    sizes: ["S", "M", "L", "XL"],
    material: "100% Pure French Linen",
    pattern: "Solid",
    fit: "Regular",
    style: "Smart Casual",
    occasion: "Casual, Office, Summer",
    season: "Summer, Spring",
    gender: "Men",
    source: "local",
    features: ["Breathable French Linen", "Spread Collar", "Mother of Pearl Buttons"],
    deliveryInformation: "🚚 Free Delivery in 2 Days",
    isBestSeller: true,
  },
  {
    id: "loc_men_top_02",
    provider: "Local",
    providerProductId: "dev_men_1002",
    title: "Heavyweight 240 GSM Oversized Black T-Shirt",
    description: "Ultra-heavyweight combed organic cotton t-shirt with dropped shoulder seams and relaxed boxy cut.",
    brand: "UrbanMinimal",
    store: "Amazon.in",
    merchant: "Amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.amazon.in/dp/B08XYZ1002",
    price: 899,
    originalPrice: 1299,
    currency: "INR",
    discountPercent: 30,
    discountPercentage: 30,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 340,
    availability: "in_stock",
    category: "Tops",
    subcategory: "T-Shirts",
    colors: ["Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    material: "100% Combed Organic Cotton",
    pattern: "Solid",
    fit: "Oversized",
    style: "Streetwear",
    occasion: "Casual, Daily",
    season: "All-Season",
    gender: "Men",
    source: "local",
    features: ["240 GSM Heavyweight Cotton", "Drop Shoulder", "Pre-shrunk fabric"],
    deliveryInformation: "🚚 Prime Express Delivery Tomorrow",
    isBestSeller: true,
  },
  {
    id: "loc_men_top_03",
    provider: "Local",
    providerProductId: "dev_men_1003",
    title: "Black Oversized Fleece Streetwear Hoodie",
    description: "360 GSM heavyweight cotton fleece pullover hoodie with kangaroo pocket and double-lined hood.",
    brand: "Drakon Streetwear",
    store: "Ajio",
    merchant: "Ajio",
    imageUrl: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.ajio.com/men-black-oversized-hoodie",
    price: 1399,
    originalPrice: 2199,
    currency: "INR",
    discountPercent: 36,
    discountPercentage: 36,
    priceStatus: "development",
    rating: 4.9,
    reviewCount: 420,
    availability: "in_stock",
    category: "Tops",
    subcategory: "Hoodie",
    colors: ["Black"],
    sizes: ["M", "L", "XL", "XXL"],
    material: "360 GSM Cotton Fleece",
    pattern: "Solid",
    fit: "Oversized",
    style: "Streetwear",
    occasion: "Casual, Loungewear",
    season: "Winter, Autumn",
    gender: "Men",
    source: "local",
    features: ["Double-lined Hood", "Ribbed Cuffs", "Kangaroo Pocket"],
    deliveryInformation: "🚚 Free Standard Delivery",
    isPopular: true,
    isBestSeller: true,
  },
  {
    id: "loc_men_top_04",
    provider: "Local",
    providerProductId: "dev_men_1004",
    title: "Slim-Fit Crimson Red Oxford Dress Shirt",
    description: "Tailored Oxford cloth shirt in deep crimson red, perfect for smart casual and semi-formal wear.",
    brand: "Oxford Studio",
    store: "Tata CLiQ",
    merchant: "Tata CLiQ",
    imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.tatacliq.com/oxford-red-shirt",
    price: 1499,
    originalPrice: 1999,
    currency: "INR",
    discountPercent: 25,
    discountPercentage: 25,
    priceStatus: "development",
    rating: 4.5,
    reviewCount: 92,
    availability: "in_stock",
    category: "Tops",
    subcategory: "Formal Shirt",
    colors: ["Red", "Burgundy"],
    sizes: ["S", "M", "L", "XL"],
    material: "100% Two-Ply Oxford Cotton",
    pattern: "Solid",
    fit: "Slim",
    style: "Formal",
    occasion: "Office, Dinner, Semi-Formal",
    season: "All-Season",
    gender: "Men",
    source: "local",
    features: ["Button-Down Collar", "Reinforced Seams", "Wrinkle-Resistant"],
    deliveryInformation: "🚚 Delivered in 3-4 Days",
  },
  {
    id: "loc_men_top_05",
    provider: "Local",
    providerProductId: "dev_men_1005",
    title: "Navy Striped Textured Knit Polo Shirt",
    description: "Classic textured knit polo with ribbed open collar, crafted from breathable combed cotton.",
    brand: "Riviera Club",
    store: "Zara",
    merchant: "Zara",
    imageUrl: "https://images.unsplash.com/photo-1625910513413-5b87dc3b4f65?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.zara.com/in/men-knit-polo-navy",
    price: 1790,
    originalPrice: 2290,
    currency: "INR",
    discountPercent: 21,
    discountPercentage: 21,
    priceStatus: "development",
    rating: 4.6,
    reviewCount: 115,
    availability: "in_stock",
    category: "Tops",
    subcategory: "Polo Shirt",
    colors: ["Navy", "White"],
    sizes: ["M", "L", "XL"],
    material: "100% Breathable Knit Cotton",
    pattern: "Striped",
    fit: "Regular",
    style: "Smart Casual",
    occasion: "Weekend, Casual Outing, Brunch",
    season: "Summer, Spring",
    gender: "Men",
    source: "local",
    features: ["Open Collar", "Textured Knit", "Ribbed Hem"],
    deliveryInformation: "🚚 Free Store Pickup or Delivery",
  },
  {
    id: "loc_men_top_06",
    provider: "Local",
    providerProductId: "dev_men_1006",
    title: "Merino Wool Camel Roll-Neck Turtleneck Sweater",
    description: "Fine gauge extra-fine Australian merino wool roll-neck sweater with a soft luxurious feel.",
    brand: "Atelier Knitwear",
    store: "H&M",
    merchant: "H&M",
    imageUrl: "https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.hm.com/in/men-merino-turtleneck-camel",
    price: 2499,
    originalPrice: 3499,
    currency: "INR",
    discountPercent: 28,
    discountPercentage: 28,
    priceStatus: "development",
    rating: 4.7,
    reviewCount: 156,
    availability: "in_stock",
    category: "Tops",
    subcategory: "Sweater",
    colors: ["Tan", "Camel"],
    sizes: ["S", "M", "L", "XL"],
    material: "100% Extra-Fine Merino Wool",
    pattern: "Solid",
    fit: "Slim",
    style: "Formal",
    occasion: "Winter Formal, Evening, Dinner",
    season: "Winter",
    gender: "Men",
    source: "local",
    features: ["Thermal Regulating", "Non-Itch Merino", "Ribbed Neckline"],
    deliveryInformation: "🚚 Free Delivery in 2-3 Days",
  },

  // --- MEN'S BOTTOMS ---
  {
    id: "loc_men_bot_01",
    provider: "Local",
    providerProductId: "dev_men_2001",
    title: "Slim Tapered Dark Indigo Selvedge Jeans",
    description: "13.5 oz raw selvedge denim with 1% elastane for comfort, custom copper rivets, and clean taper.",
    brand: "Indigo Craft",
    store: "Myntra",
    merchant: "Myntra",
    imageUrl: "https://images.unsplash.com/photo-1542272604-780c96856592?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.myntra.com/jeans/indigo-craft-selvedge",
    price: 2499,
    originalPrice: 3499,
    currency: "INR",
    discountPercent: 28,
    discountPercentage: 28,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 290,
    availability: "in_stock",
    category: "Bottoms",
    subcategory: "Jeans",
    colors: ["Blue", "Navy"],
    sizes: ["30", "32", "34", "36"],
    material: "99% Cotton, 1% Elastane",
    pattern: "Solid",
    fit: "Slim",
    style: "Casual",
    occasion: "Casual, Daily, Evening",
    season: "All-Season",
    gender: "Men",
    source: "local",
    features: ["13.5 oz Selvedge Denim", "Comfort Stretch", "Chain-Stitched Hem"],
    deliveryInformation: "🚚 Fast Express Delivery",
    isBestSeller: true,
  },
  {
    id: "loc_men_bot_02",
    provider: "Local",
    providerProductId: "dev_men_2002",
    title: "Tailored Navy Italian Cotton Chinos",
    description: "Mid-rise chinos crafted from stretch cotton twill with welt back pockets and horn button closure.",
    brand: "Sartorial Works",
    store: "Tata CLiQ",
    merchant: "Tata CLiQ",
    imageUrl: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.tatacliq.com/navy-tailored-chinos",
    price: 1999,
    originalPrice: 2799,
    currency: "INR",
    discountPercent: 28,
    discountPercentage: 28,
    priceStatus: "development",
    rating: 4.7,
    reviewCount: 165,
    availability: "in_stock",
    category: "Bottoms",
    subcategory: "Chinos",
    colors: ["Navy", "Blue"],
    sizes: ["30", "32", "34", "36"],
    material: "98% Cotton Twill, 2% Spandex",
    pattern: "Solid",
    fit: "Tailored",
    style: "Smart Casual",
    occasion: "Office, Smart Casual, Dinner",
    season: "All-Season",
    gender: "Men",
    source: "local",
    features: ["Stretch Cotton Twill", "Slanted Front Pockets", "Wrinkle Guard"],
    deliveryInformation: "🚚 Delivered in 2-3 Days",
    isBestSeller: true,
  },
  {
    id: "loc_men_bot_03",
    provider: "Local",
    providerProductId: "dev_men_2003",
    title: "Relaxed Pleated Linen-Blend Trousers",
    description: "Airy linen-cotton blend trousers featuring single front pleats, elasticated back waist, and wide drape.",
    brand: "Sol & Linen",
    store: "Zara",
    merchant: "Zara",
    imageUrl: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.zara.com/in/men-pleated-linen-trousers-sand",
    price: 2290,
    originalPrice: 2990,
    currency: "INR",
    discountPercent: 23,
    discountPercentage: 23,
    priceStatus: "development",
    rating: 4.6,
    reviewCount: 130,
    availability: "in_stock",
    category: "Bottoms",
    subcategory: "Trousers",
    colors: ["Beige", "Tan"],
    sizes: ["30", "32", "34", "36"],
    material: "55% Linen, 45% Cotton",
    pattern: "Solid",
    fit: "Relaxed",
    style: "Minimalist",
    occasion: "Summer, Vacation, Casual",
    season: "Summer, Spring",
    gender: "Men",
    source: "local",
    features: ["Breathable Linen Blend", "Single Front Pleats", "Elastic Back Waist"],
    deliveryInformation: "🚚 Free Store Pickup or Delivery",
  },
  {
    id: "loc_men_bot_04",
    provider: "Local",
    providerProductId: "dev_men_2004",
    title: "Multi-Pocket Utility Techwear Cargo Pants",
    description: "Durable ripstop cotton cargo pants with modular flap pockets, drawcord cuffs, and relaxed street fit.",
    brand: "Apex Modular",
    store: "Amazon.in",
    merchant: "Amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.amazon.in/dp/B09CARGO104",
    price: 1599,
    originalPrice: 2299,
    currency: "INR",
    discountPercent: 30,
    discountPercentage: 30,
    priceStatus: "development",
    rating: 4.7,
    reviewCount: 210,
    availability: "in_stock",
    category: "Bottoms",
    subcategory: "Cargo",
    colors: ["Black", "Olive"],
    sizes: ["30", "32", "34", "36"],
    material: "100% Ripstop Cotton",
    pattern: "Solid",
    fit: "Relaxed",
    style: "Streetwear",
    occasion: "Casual, Outdoor, Streetwear",
    season: "All-Season",
    gender: "Men",
    source: "local",
    features: ["Heavy Ripstop Fabric", "6 Functional Pockets", "Adjustable Ankle Cuffs"],
    deliveryInformation: "🚚 Prime Express Tomorrow",
    isPopular: true,
  },

  // --- MEN'S ETHNIC WEAR ---
  {
    id: "loc_men_eth_01",
    provider: "Local",
    providerProductId: "dev_men_3001",
    title: "Royal Emerald Handloom Silk Kurta Pyjama Set",
    description: "Pure Dupion silk kurta in rich emerald green with intricate mandarin collar zari embroidery and churidar pyjama.",
    brand: "Manyavar Heritage",
    store: "Manyavar",
    merchant: "Manyavar",
    imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.manyavar.com/men-emerald-silk-kurta-set",
    price: 3499,
    originalPrice: 4999,
    currency: "INR",
    discountPercent: 30,
    discountPercentage: 30,
    priceStatus: "development",
    rating: 4.9,
    reviewCount: 380,
    availability: "in_stock",
    category: "Ethnic Wear",
    subcategory: "Kurta Pyjama",
    colors: ["Green", "Gold"],
    sizes: ["38", "40", "42", "44"],
    material: "Pure Dupion Handloom Silk",
    pattern: "Embroidered",
    fit: "Regular",
    style: "Traditional",
    occasion: "Weddings / Functions, Diwali, Festive",
    season: "All-Season",
    gender: "Men",
    source: "local",
    features: ["Mandarin Zari Collar", "Includes Churidar Pyjama", "Rich Emerald Sheen"],
    deliveryInformation: "🚚 Free Express Delivery in 2 Days",
    isBestSeller: true,
  },
  {
    id: "loc_men_eth_02",
    provider: "Local",
    providerProductId: "dev_men_3002",
    title: "Ivory Lucknowi Chikankari Cotton Kurta",
    description: "Handcrafted pure cotton kurta featuring fine Lucknowi tone-on-tone thread embroidery and side pockets.",
    brand: "Awadh Weaves",
    store: "Myntra",
    merchant: "Myntra",
    imageUrl: "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.myntra.com/ethnic/lucknowi-chikankari-ivory",
    price: 1999,
    originalPrice: 2899,
    currency: "INR",
    discountPercent: 31,
    discountPercentage: 31,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 240,
    availability: "in_stock",
    category: "Ethnic Wear",
    subcategory: "Kurta",
    colors: ["White", "Cream"],
    sizes: ["38", "40", "42", "44"],
    material: "100% Breathable Mulmul Cotton",
    pattern: "Embroidered",
    fit: "Regular",
    style: "Traditional",
    occasion: "Festive, Puja, Summer Weddings",
    season: "Summer, Spring",
    gender: "Men",
    source: "local",
    features: ["Authentic Hand Chikankari", "Pure Mulmul Cotton", "Mandarin Placket"],
    deliveryInformation: "🚚 Free Delivery in 3 Days",
  },
  {
    id: "loc_men_eth_03",
    provider: "Local",
    providerProductId: "dev_men_3003",
    title: "Rich Crimson Red Raw Silk Festive Kurta",
    description: "Vibrant crimson red raw silk kurta with textured weave and subtle metallic button details under ₹2000.",
    brand: "Vedic Roots",
    store: "Amazon.in",
    merchant: "Amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.amazon.in/dp/B08RED103",
    price: 1599,
    originalPrice: 2399,
    currency: "INR",
    discountPercent: 33,
    discountPercentage: 33,
    priceStatus: "development",
    rating: 4.6,
    reviewCount: 175,
    availability: "in_stock",
    category: "Ethnic Wear",
    subcategory: "Kurta",
    colors: ["Red", "Maroon"],
    sizes: ["38", "40", "42", "44"],
    material: "Raw Art Silk Blend",
    pattern: "Solid",
    fit: "Regular",
    style: "Traditional",
    occasion: "Weddings / Functions, Sangeet, Festive",
    season: "All-Season",
    gender: "Men",
    source: "local",
    features: ["Rich Textured Silk Blend", "Metallic Buttons", "Mandarin Collar"],
    deliveryInformation: "🚚 Prime Express Tomorrow",
    isPopular: true,
  },
  {
    id: "loc_men_eth_04",
    provider: "Local",
    providerProductId: "dev_men_3004",
    title: "Brocade Woven Mustard Gold Nehru Jacket",
    description: "Opulent Jacquard woven Nehru jacket with mandarin collar and welt pockets, ideal for wedding layering.",
    brand: "Kora Royal",
    store: "Ajio",
    merchant: "Ajio",
    imageUrl: "https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.ajio.com/men-gold-brocade-nehru-jacket",
    price: 2499,
    originalPrice: 3499,
    currency: "INR",
    discountPercent: 28,
    discountPercentage: 28,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 195,
    availability: "in_stock",
    category: "Ethnic Wear",
    subcategory: "Nehru Jacket",
    colors: ["Yellow", "Gold"],
    sizes: ["38", "40", "42", "44"],
    material: "Woven Jacquard Brocade",
    pattern: "Self Design",
    fit: "Tailored",
    style: "Traditional",
    occasion: "Weddings / Functions, Haldi, Festive",
    season: "All-Season",
    gender: "Men",
    source: "local",
    features: ["Intricate Floral Jacquard", "Satin Lining", "Mandarin Collar"],
    deliveryInformation: "🚚 Delivered in 2-3 Days",
  },

  // --- MEN'S OUTERWEAR ---
  {
    id: "loc_men_out_01",
    provider: "Local",
    providerProductId: "dev_men_4001",
    title: "Structured Italian Wool Midnight Navy Blazer",
    description: "Double-vented tailored blazer in 100% fine Italian wool with notch lapels and unpadded natural shoulders.",
    brand: "Milano Tailors",
    store: "Zara",
    merchant: "Zara",
    imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.zara.com/in/men-navy-wool-blazer",
    price: 4990,
    originalPrice: 6990,
    currency: "INR",
    discountPercent: 28,
    discountPercentage: 28,
    priceStatus: "development",
    rating: 4.9,
    reviewCount: 215,
    availability: "in_stock",
    category: "Outerwear",
    subcategory: "Blazer",
    colors: ["Navy", "Blue"],
    sizes: ["38", "40", "42", "44"],
    material: "100% Fine Italian Wool",
    pattern: "Solid",
    fit: "Tailored",
    style: "Formal",
    occasion: "Office, Job Interview, Formal Gala, Conference",
    season: "All-Season, Autumn, Winter",
    gender: "Men",
    source: "local",
    features: ["Super 120s Wool", "Half-Canvas Construction", "Corozo Nut Buttons"],
    deliveryInformation: "🚚 Free Express Shipping",
    isBestSeller: true,
  },
  {
    id: "loc_men_out_02",
    provider: "Local",
    providerProductId: "dev_men_4002",
    title: "Vintage Washed Rugged Denim Trucker Jacket",
    description: "Heavy 14 oz indigo denim jacket with authentic wash fading, chest flap pockets, and metal shank buttons.",
    brand: "Rough & Co",
    store: "Myntra",
    merchant: "Myntra",
    imageUrl: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.myntra.com/jackets/denim-trucker-vintage",
    price: 2199,
    originalPrice: 3199,
    currency: "INR",
    discountPercent: 31,
    discountPercentage: 31,
    priceStatus: "development",
    rating: 4.7,
    reviewCount: 310,
    availability: "in_stock",
    category: "Outerwear",
    subcategory: "Denim Jacket",
    colors: ["Blue"],
    sizes: ["S", "M", "L", "XL"],
    material: "100% Heavy Cotton Denim",
    pattern: "Solid",
    fit: "Regular",
    style: "Casual",
    occasion: "Casual, Weekend, Travel",
    season: "Spring, Autumn, Winter",
    gender: "Men",
    source: "local",
    features: ["14 oz Rigid Denim", "Hand-Distressed Detailing", "Dual Chest Pockets"],
    deliveryInformation: "🚚 Free Delivery in 2 Days",
  },
  {
    id: "loc_men_out_03",
    provider: "Local",
    providerProductId: "dev_men_4003",
    title: "Premium Grain Leather Minimalist Biker Jacket",
    description: "Top-grain genuine buffalo leather jacket with asymmetrical silver zipper and quilted satin lining.",
    brand: "Nighthawk Leather",
    store: "Tata CLiQ",
    merchant: "Tata CLiQ",
    imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.tatacliq.com/leather-biker-jacket-black",
    price: 5499,
    originalPrice: 7999,
    currency: "INR",
    discountPercent: 31,
    discountPercentage: 31,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 140,
    availability: "in_stock",
    category: "Outerwear",
    subcategory: "Leather Jacket",
    colors: ["Black"],
    sizes: ["M", "L", "XL"],
    material: "100% Top-Grain Leather",
    pattern: "Solid",
    fit: "Slim",
    style: "Streetwear",
    occasion: "Night Out, Party, Casual",
    season: "Winter, Autumn",
    gender: "Men",
    source: "local",
    features: ["Heavy YKK Zippers", "Quilted Satin Lining", "Genuine Top-Grain Leather"],
    deliveryInformation: "🚚 Free Insured Delivery",
  },

  // --- MEN'S FOOTWEAR ---
  {
    id: "loc_men_foot_01",
    provider: "Local",
    providerProductId: "dev_men_5001",
    title: "Minimalist Low-Top White Leather Sneakers",
    description: "Clean Italian nappa leather sneakers with cushioned memory foam footbed and durable margom rubber cupsole.",
    brand: "Monochrome Studio",
    store: "Amazon.in",
    merchant: "Amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.amazon.in/dp/B08WHITE501",
    price: 2499,
    originalPrice: 3499,
    currency: "INR",
    discountPercent: 28,
    discountPercentage: 28,
    priceStatus: "development",
    rating: 4.9,
    reviewCount: 460,
    availability: "in_stock",
    category: "Footwear",
    subcategory: "Sneakers",
    colors: ["White"],
    sizes: ["7", "8", "9", "10", "11"],
    material: "Full-Grain Italian Nappa Leather",
    pattern: "Solid",
    fit: "Regular",
    style: "Minimalist",
    occasion: "Casual, Smart Casual, Daily, Travel",
    season: "All-Season",
    gender: "Men",
    source: "local",
    features: ["Full-Grain Nappa Leather", "Margom Rubber Cupsole", "Memory Foam Insole"],
    deliveryInformation: "🚚 Prime Express Tomorrow",
    isBestSeller: true,
  },
  {
    id: "loc_men_foot_02",
    provider: "Local",
    providerProductId: "dev_men_5002",
    title: "Handcrafted Dark Brown Leather Penny Loafers",
    description: "Classic Goodyear-welted penny loafers in rich burnished calfskin with leather sole and stacked heel.",
    brand: "Cobbler & Sons",
    store: "Myntra",
    merchant: "Myntra",
    imageUrl: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.myntra.com/shoes/leather-penny-loafers-brown",
    price: 2999,
    originalPrice: 4299,
    currency: "INR",
    discountPercent: 30,
    discountPercentage: 30,
    priceStatus: "development",
    rating: 4.7,
    reviewCount: 185,
    availability: "in_stock",
    category: "Footwear",
    subcategory: "Loafers",
    colors: ["Brown", "Tan"],
    sizes: ["7", "8", "9", "10", "11"],
    material: "Burnished Calfskin Leather",
    pattern: "Solid",
    fit: "Regular",
    style: "Smart Casual",
    occasion: "Office, Smart Casual, Dinner, Weddings / Functions",
    season: "All-Season",
    gender: "Men",
    source: "local",
    features: ["Goodyear Welted", "Burnished Calfskin", "Cushioned Arch Support"],
    deliveryInformation: "🚚 Free Delivery in 2 Days",
  },
  {
    id: "loc_men_foot_03",
    provider: "Local",
    providerProductId: "dev_men_5003",
    title: "Handcrafted Traditional Gold Zari Mojari Jutti",
    description: "Authentic handcrafted ethnic jutti in ivory and gold thread embroidery with padded soft leather sole.",
    brand: "Virasat Footwear",
    store: "Manyavar",
    merchant: "Manyavar",
    imageUrl: "https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.manyavar.com/men-gold-zari-mojari",
    price: 1899,
    originalPrice: 2499,
    currency: "INR",
    discountPercent: 24,
    discountPercentage: 24,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 210,
    availability: "in_stock",
    category: "Footwear",
    subcategory: "Jutti",
    colors: ["Gold", "White"],
    sizes: ["7", "8", "9", "10", "11"],
    material: "Embroidered Silk & Genuine Leather Sole",
    pattern: "Embroidered",
    fit: "Regular",
    style: "Traditional",
    occasion: "Weddings / Functions, Sangeet, Festive",
    season: "All-Season",
    gender: "Men",
    source: "local",
    features: ["Intricate Gold Zari", "Bite-Free Padded Heel", "Genuine Leather Sole"],
    deliveryInformation: "🚚 Delivered in 3 Days",
  },

  // =========================================================================
  // WOMEN'S COLLECTION
  // =========================================================================

  // --- WOMEN'S DRESSES ---
  {
    id: "loc_wom_drs_01",
    provider: "Local",
    providerProductId: "dev_wom_1001",
    title: "Tiered Floral Chiffon Summer Maxi Dress",
    description: "Flowing airy chiffon maxi dress with delicate floral prints, tiered ruffles, and adjustable waist tie.",
    brand: "Meadow Bloom",
    store: "Myntra",
    merchant: "Myntra",
    imageUrl: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.myntra.com/dresses/meadow-floral-maxi",
    price: 2199,
    originalPrice: 3299,
    currency: "INR",
    discountPercent: 33,
    discountPercentage: 33,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 320,
    availability: "in_stock",
    category: "Dresses",
    subcategory: "Summer Dress",
    colors: ["Pink", "Yellow", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "100% Breathable Chiffon Georgette",
    pattern: "Floral",
    fit: "Relaxed",
    style: "Romantic",
    occasion: "Summer, Vacation, Brunch, Casual Outing",
    season: "Summer, Spring",
    gender: "Women",
    source: "local",
    features: ["Tiered Ruffle Hem", "Adjustable Waist Tie", "Soft Inner Lining"],
    deliveryInformation: "🚚 Free Express Delivery",
    isBestSeller: true,
  },
  {
    id: "loc_wom_drs_02",
    provider: "Local",
    providerProductId: "dev_wom_1002",
    title: "Emerald Green Pure Mulberry Silk Slip Midi Dress",
    description: "Luxurious bias-cut mulberry silk slip dress with cowled neckline and sleek side slit for evening elegance.",
    brand: "Lumière Silk",
    store: "Zara",
    merchant: "Zara",
    imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.zara.com/in/women-emerald-silk-slip-dress",
    price: 3290,
    originalPrice: 4490,
    currency: "INR",
    discountPercent: 26,
    discountPercentage: 26,
    priceStatus: "development",
    rating: 4.9,
    reviewCount: 245,
    availability: "in_stock",
    category: "Dresses",
    subcategory: "Evening Gown",
    colors: ["Green", "Emerald"],
    sizes: ["XS", "S", "M", "L"],
    material: "100% Pure Mulberry Silk",
    pattern: "Solid",
    fit: "Slim",
    style: "Minimalist",
    occasion: "Date, Party, Evening, Dinner, Weddings / Functions",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["19 Momme Pure Silk", "Cowl Neckline", "Bias-Cut Drape"],
    deliveryInformation: "🚚 Free Store Delivery",
    isBestSeller: true,
  },
  {
    id: "loc_wom_drs_03",
    provider: "Local",
    providerProductId: "dev_wom_1003",
    title: "Terracotta Tailored Linen Wrap Midi Dress",
    description: "Breathable pure linen wrap dress with side tie fastening, structured V-neckline, and functional pockets.",
    brand: "Aura Linen",
    store: "Ajio",
    merchant: "Ajio",
    imageUrl: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.ajio.com/women-terracotta-linen-wrap-dress",
    price: 1899,
    originalPrice: 2699,
    currency: "INR",
    discountPercent: 29,
    discountPercentage: 29,
    priceStatus: "development",
    rating: 4.7,
    reviewCount: 160,
    availability: "in_stock",
    category: "Dresses",
    subcategory: "Midi Dress",
    colors: ["Orange", "Tan", "Brown"],
    sizes: ["S", "M", "L", "XL"],
    material: "100% Pure European Linen",
    pattern: "Solid",
    fit: "Regular",
    style: "Smart Casual",
    occasion: "Brunch, Casual, Office, Summer",
    season: "Summer, Spring",
    gender: "Women",
    source: "local",
    features: ["Functional Side Pockets", "True Wrap Silhouette", "Pure European Linen"],
    deliveryInformation: "🚚 Delivered in 2-3 Days",
  },
  {
    id: "loc_wom_drs_04",
    provider: "Local",
    providerProductId: "dev_wom_1004",
    title: "Ruby Red Elegant Cocktail Party Dress",
    description: "Structured A-line cocktail dress in rich ruby red with boat neckline and pleated skirt.",
    brand: "Glamour Society",
    store: "Tata CLiQ",
    merchant: "Tata CLiQ",
    imageUrl: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.tatacliq.com/ruby-red-cocktail-dress",
    price: 2499,
    originalPrice: 3599,
    currency: "INR",
    discountPercent: 30,
    discountPercentage: 30,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 190,
    availability: "in_stock",
    category: "Dresses",
    subcategory: "Cocktail Dress",
    colors: ["Red", "Ruby"],
    sizes: ["XS", "S", "M", "L"],
    material: "Heavy Crepe Poly-Blend",
    pattern: "Solid",
    fit: "Tailored",
    style: "Formal",
    occasion: "Party, Formal Gala, Celebration, Dinner",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["Concealed Back Zipper", "Flattering Fit & Flare", "Structured Bodice"],
    deliveryInformation: "🚚 Free Express Delivery",
    isPopular: true,
  },

  // --- WOMEN'S ETHNIC WEAR ---
  {
    id: "loc_wom_eth_01",
    provider: "Local",
    providerProductId: "dev_wom_2001",
    title: "Dusty Rose Embroidered Anarkali Kurti Set",
    description: "Floor-length Georgette Anarkali kurti with delicate mirror-work embroidery, churidar pants, and scalloped dupatta.",
    brand: "Biba Royale",
    store: "Myntra",
    merchant: "Myntra",
    imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.myntra.com/ethnic/biba-dusty-rose-anarkali",
    price: 3299,
    originalPrice: 4899,
    currency: "INR",
    discountPercent: 32,
    discountPercentage: 32,
    priceStatus: "development",
    rating: 4.9,
    reviewCount: 410,
    availability: "in_stock",
    category: "Ethnic Wear",
    subcategory: "Anarkali Kurti",
    colors: ["Pink", "Rose"],
    sizes: ["S", "M", "L", "XL"],
    material: "Pure Georgette with Shantoon Lining",
    pattern: "Embroidered",
    fit: "Regular",
    style: "Traditional",
    occasion: "Weddings / Functions, Sangeet, Festive, Reception",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["Real Mirror Work", "Complete 3-Piece Set", "Scalloped Organza Dupatta"],
    deliveryInformation: "🚚 Free Delivery in 2 Days",
    isBestSeller: true,
  },
  {
    id: "loc_wom_eth_02",
    provider: "Local",
    providerProductId: "dev_wom_2002",
    title: "Crimson Red Pure Banarasi Silk Zari Saree",
    description: "Authentic Handloom Banarasi Katan silk saree woven with rich golden Kadwa floral jaal and unstitched blouse piece.",
    brand: "Varanasi Handlooms",
    store: "Tata CLiQ",
    merchant: "Tata CLiQ",
    imageUrl: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.tatacliq.com/banarasi-silk-saree-crimson",
    price: 4999,
    originalPrice: 7999,
    currency: "INR",
    discountPercent: 37,
    discountPercentage: 37,
    priceStatus: "development",
    rating: 4.9,
    reviewCount: 520,
    availability: "in_stock",
    category: "Ethnic Wear",
    subcategory: "Saree",
    colors: ["Red", "Gold"],
    sizes: ["Free Size"],
    material: "100% Pure Katan Silk",
    pattern: "Zari Woven",
    fit: "Regular",
    style: "Traditional",
    occasion: "Weddings / Functions, Puja, Diwali, Festive",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["Silk Mark Certified", "Kadwa Gold Weave", "Matching Blouse Piece"],
    deliveryInformation: "🚚 Insured Express Shipping",
    isBestSeller: true,
  },
  {
    id: "loc_wom_eth_03",
    provider: "Local",
    providerProductId: "dev_wom_2003",
    title: "Pastel Mint Floral Embroidered Lehenga Choli",
    description: "Exquisite net lehenga embellished with sequins, resham thread florals, cancan lining, and matching embellished choli.",
    brand: "Riwayat Couture",
    store: "Ajio",
    merchant: "Ajio",
    imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.ajio.com/women-mint-embroidered-lehenga",
    price: 5999,
    originalPrice: 8999,
    currency: "INR",
    discountPercent: 33,
    discountPercentage: 33,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 280,
    availability: "in_stock",
    category: "Ethnic Wear",
    subcategory: "Lehenga",
    colors: ["Green", "Mint"],
    sizes: ["S", "M", "L", "XL"],
    material: "Soft Net with Satin & Cancan Lining",
    pattern: "Embroidered",
    fit: "Regular",
    style: "Traditional",
    occasion: "Weddings / Functions, Sangeet, Reception",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["Double Cancan Flare", "Resham & Sequin Work", "Embroidered Dupatta"],
    deliveryInformation: "🚚 Delivered in 3-4 Days",
    isPopular: true,
  },
  {
    id: "loc_wom_eth_04",
    provider: "Local",
    providerProductId: "dev_wom_2004",
    title: "Sky Blue Handcrafted Lucknowi Chikankari Kurti",
    description: "Pure cotton mulmul kurti featuring authentic hand-embroidered floral motifs with matching slip.",
    brand: "Chikan Heritage",
    store: "Amazon.in",
    merchant: "Amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.amazon.in/dp/B09BLUE2004",
    price: 1399,
    originalPrice: 1999,
    currency: "INR",
    discountPercent: 30,
    discountPercentage: 30,
    priceStatus: "development",
    rating: 4.7,
    reviewCount: 215,
    availability: "in_stock",
    category: "Ethnic Wear",
    subcategory: "Kurti",
    colors: ["Blue", "Sky Blue"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    material: "100% Pure Mulmul Cotton",
    pattern: "Embroidered",
    fit: "Regular",
    style: "Traditional",
    occasion: "Casual, Daily, Office, Festive",
    season: "Summer, Spring",
    gender: "Women",
    source: "local",
    features: ["Handcrafted Lucknowi Motifs", "Includes Matching Cotton Slip", "Breathable Fabric"],
    deliveryInformation: "🚚 Prime Delivery Tomorrow",
  },

  // --- WOMEN'S TOPS & BLOUSE ---
  {
    id: "loc_wom_top_01",
    provider: "Local",
    providerProductId: "dev_wom_3001",
    title: "Ivory Pure Silk Button-Up Tailored Blouse",
    description: "Elegant sandwashed silk blouse with mother-of-pearl buttons, classic collar, and gentle curved hem.",
    brand: "Lumière Silk",
    store: "Zara",
    merchant: "Zara",
    imageUrl: "https://images.unsplash.com/photo-1551803091-e20673f15770?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.zara.com/in/women-silk-blouse-ivory",
    price: 2490,
    originalPrice: 3290,
    currency: "INR",
    discountPercent: 24,
    discountPercentage: 24,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 175,
    availability: "in_stock",
    category: "Tops",
    subcategory: "Blouse",
    colors: ["White", "Cream"],
    sizes: ["XS", "S", "M", "L"],
    material: "100% Sandwashed Silk",
    pattern: "Solid",
    fit: "Regular",
    style: "Formal",
    occasion: "Office, Meeting, Job Interview, Dinner",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["Mother of Pearl Buttons", "Sandwashed Drape", "Reinforced Placket"],
    deliveryInformation: "🚚 Free Store Pickup or Delivery",
    isBestSeller: true,
  },
  {
    id: "loc_wom_top_02",
    provider: "Local",
    providerProductId: "dev_wom_3002",
    title: "Burgundy Sweetheart Ribbed Knit Long-Sleeve Top",
    description: "Form-fitting ribbed stretch knit top featuring a structured sweetheart neckline and long sleeves.",
    brand: "Studio Silhouette",
    store: "Myntra",
    merchant: "Myntra",
    imageUrl: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.myntra.com/tops/sweetheart-ribbed-burgundy",
    price: 1199,
    originalPrice: 1799,
    currency: "INR",
    discountPercent: 33,
    discountPercentage: 33,
    priceStatus: "development",
    rating: 4.6,
    reviewCount: 145,
    availability: "in_stock",
    category: "Tops",
    subcategory: "Knit Top",
    colors: ["Burgundy", "Red"],
    sizes: ["XS", "S", "M", "L"],
    material: "95% Cotton Knit, 5% Elastane",
    pattern: "Solid",
    fit: "Slim",
    style: "Smart Casual",
    occasion: "Date, Casual Outing, Dinner",
    season: "Autumn, Spring, Winter",
    gender: "Women",
    source: "local",
    features: ["Sculpted Sweetheart Neck", "Fine Ribbed Texture", "Shape Retention"],
    deliveryInformation: "🚚 Delivered in 2 Days",
  },
  {
    id: "loc_wom_top_03",
    provider: "Local",
    providerProductId: "dev_wom_3003",
    title: "Oversized Lavender Drop-Shoulder Cotton Hoodie",
    description: "Cozy 320 GSM brushed back organic cotton hoodie with tonal embroidered logo and ribbed trims.",
    brand: "Pastel Cloud",
    store: "H&M",
    merchant: "H&M",
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.hm.com/in/women-lavender-oversized-hoodie",
    price: 1499,
    originalPrice: 2299,
    currency: "INR",
    discountPercent: 35,
    discountPercentage: 35,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 310,
    availability: "in_stock",
    category: "Tops",
    subcategory: "Hoodie",
    colors: ["Pink", "Purple"],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "100% Organic Cotton Fleece",
    pattern: "Solid",
    fit: "Oversized",
    style: "Streetwear",
    occasion: "Casual, Loungewear, Travel",
    season: "Winter, Autumn",
    gender: "Women",
    source: "local",
    features: ["320 GSM Brushed Fleece", "Relaxed Drop Shoulder", "Tonal Embroidery"],
    deliveryInformation: "🚚 Free Delivery in 3 Days",
    isPopular: true,
  },

  // --- WOMEN'S BOTTOMS ---
  {
    id: "loc_wom_bot_01",
    provider: "Local",
    providerProductId: "dev_wom_4001",
    title: "High-Waisted Wide-Leg Camel Tailored Trousers",
    description: "Flowing wide-leg trousers featuring front pleats, high-rise waist with belt loops, and clean slant pockets.",
    brand: "Modern Tailor",
    store: "Zara",
    merchant: "Zara",
    imageUrl: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.zara.com/in/women-wide-leg-camel-trousers",
    price: 2490,
    originalPrice: 3490,
    currency: "INR",
    discountPercent: 28,
    discountPercentage: 28,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 260,
    availability: "in_stock",
    category: "Bottoms",
    subcategory: "Trousers",
    colors: ["Tan", "Camel", "Beige"],
    sizes: ["26", "28", "30", "32", "34"],
    material: "Poly-Viscose Stretch Twill",
    pattern: "Solid",
    fit: "Tailored",
    style: "Formal",
    occasion: "Office, Job Interview, Formal, Dinner",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["High-Rise Waist", "Deep Front Pleats", "Flowing Wide Leg"],
    deliveryInformation: "🚚 Free Store Pickup or Delivery",
    isBestSeller: true,
  },
  {
    id: "loc_wom_bot_02",
    provider: "Local",
    providerProductId: "dev_wom_4002",
    title: "Vintage High-Rise Straight Ankle Jeans",
    description: "Classic 90s vintage wash rigid cotton denim with high-rise waist, straight silhouette, and cropped ankle hem.",
    brand: "Denim Archive",
    store: "Myntra",
    merchant: "Myntra",
    imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.myntra.com/jeans/vintage-straight-ankle-women",
    price: 1999,
    originalPrice: 2899,
    currency: "INR",
    discountPercent: 31,
    discountPercentage: 31,
    priceStatus: "development",
    rating: 4.7,
    reviewCount: 380,
    availability: "in_stock",
    category: "Bottoms",
    subcategory: "Jeans",
    colors: ["Blue"],
    sizes: ["26", "28", "30", "32"],
    material: "99% Cotton, 1% Spandex",
    pattern: "Solid",
    fit: "Regular",
    style: "Casual",
    occasion: "Casual, Daily, Weekend",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["High-Rise Waist", "Authentic 90s Wash", "Cropped Ankle Hem"],
    deliveryInformation: "🚚 Fast Express Delivery",
    isBestSeller: true,
  },
  {
    id: "loc_wom_bot_03",
    provider: "Local",
    providerProductId: "dev_wom_4003",
    title: "Champagne Gold Pleated Satin Midi Skirt",
    description: "Lustrous accordion-pleated midi skirt in soft champagne gold satin with an elasticated waistband.",
    brand: "Luxe Pleats",
    store: "Ajio",
    merchant: "Ajio",
    imageUrl: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.ajio.com/women-champagne-pleated-satin-skirt",
    price: 1799,
    originalPrice: 2599,
    currency: "INR",
    discountPercent: 30,
    discountPercentage: 30,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 195,
    availability: "in_stock",
    category: "Bottoms",
    subcategory: "Skirt",
    colors: ["Gold", "Yellow", "Cream"],
    sizes: ["S", "M", "L", "XL"],
    material: "High-Shine Satin Poly",
    pattern: "Solid",
    fit: "Relaxed",
    style: "Romantic",
    occasion: "Party, Date, Brunch, Weddings / Functions",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["Permanent Accordion Pleats", "Comfort Elastic Waist", "High-Gloss Satin"],
    deliveryInformation: "🚚 Delivered in 2-3 Days",
  },

  // --- WOMEN'S OUTERWEAR ---
  {
    id: "loc_wom_out_01",
    provider: "Local",
    providerProductId: "dev_wom_5001",
    title: "Tailored Double-Breasted Oatmeal Wool Blazer",
    description: "Structured double-breasted blazer with peak lapels, tortoise-shell buttons, and fully lined interior.",
    brand: "Atelier Paris",
    store: "Zara",
    merchant: "Zara",
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.zara.com/in/women-double-breasted-blazer-oatmeal",
    price: 3990,
    originalPrice: 5590,
    currency: "INR",
    discountPercent: 28,
    discountPercentage: 28,
    priceStatus: "development",
    rating: 4.9,
    reviewCount: 220,
    availability: "in_stock",
    category: "Outerwear",
    subcategory: "Blazer",
    colors: ["Beige", "Tan", "Cream"],
    sizes: ["XS", "S", "M", "L"],
    material: "Wool-Viscose Blend",
    pattern: "Solid",
    fit: "Tailored",
    style: "Formal",
    occasion: "Office, Job Interview, Meeting, Smart Casual",
    season: "All-Season, Autumn, Winter",
    gender: "Women",
    source: "local",
    features: ["Peak Lapels", "Tortoise Shell Buttons", "Double-Breasted Cut"],
    deliveryInformation: "🚚 Free Store Pickup or Delivery",
    isBestSeller: true,
  },
  {
    id: "loc_wom_out_02",
    provider: "Local",
    providerProductId: "dev_wom_5002",
    title: "Classic Belted Wool-Blend Camel Trench Coat",
    description: "Timeless longline belted trench coat with storm flap, notched collar, and warm wool-blend fabric.",
    brand: "Heritage Outerwear",
    store: "Tata CLiQ",
    merchant: "Tata CLiQ",
    imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.tatacliq.com/camel-wool-trench-coat-women",
    price: 4499,
    originalPrice: 6499,
    currency: "INR",
    discountPercent: 30,
    discountPercentage: 30,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 170,
    availability: "in_stock",
    category: "Outerwear",
    subcategory: "Trench Coat",
    colors: ["Tan", "Camel"],
    sizes: ["S", "M", "L", "XL"],
    material: "70% Wool, 30% Polyester",
    pattern: "Solid",
    fit: "Regular",
    style: "Formal",
    occasion: "Winter Formal, Travel, Evening",
    season: "Winter",
    gender: "Women",
    source: "local",
    features: ["Detachable Waist Belt", "Wind-Resistant Wool Blend", "Satin Inner Lining"],
    deliveryInformation: "🚚 Free Express Shipping",
  },

  // --- WOMEN'S FOOTWEAR ---
  {
    id: "loc_wom_foot_01",
    provider: "Local",
    providerProductId: "dev_wom_6001",
    title: "Nude Leather Block-Heel Strappy Sandals",
    description: "Versatile 2.5-inch block heel sandals in soft nude Italian nappa leather with adjustable ankle buckle.",
    brand: "Bella Donna",
    store: "Myntra",
    merchant: "Myntra",
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.myntra.com/heels/nude-leather-block-sandals",
    price: 1999,
    originalPrice: 2799,
    currency: "INR",
    discountPercent: 28,
    discountPercentage: 28,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 340,
    availability: "in_stock",
    category: "Footwear",
    subcategory: "Sandals",
    colors: ["Tan", "Nude", "Beige"],
    sizes: ["5", "6", "7", "8", "9"],
    material: "Soft Italian Nappa Leather",
    pattern: "Solid",
    fit: "Regular",
    style: "Smart Casual",
    occasion: "Weddings / Functions, Party, Date, Brunch, Office",
    season: "Summer, Spring, All-Season",
    gender: "Women",
    source: "local",
    features: ["Comfort 2.5\" Block Heel", "Padded Memory Foam Footbed", "Non-Slip Sole"],
    deliveryInformation: "🚚 Free Express Delivery in 2 Days",
    isBestSeller: true,
  },
  {
    id: "loc_wom_foot_02",
    provider: "Local",
    providerProductId: "dev_wom_6002",
    title: "Minimalist White Leather Court Tennis Sneakers",
    description: "Ultra-clean white leather sneakers with subtle rose-gold eyelets and lightweight cushioned EVA sole.",
    brand: "Studio Court",
    store: "Amazon.in",
    merchant: "Amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.amazon.in/dp/B08WOMEN502",
    price: 2299,
    originalPrice: 3199,
    currency: "INR",
    discountPercent: 28,
    discountPercentage: 28,
    priceStatus: "development",
    rating: 4.9,
    reviewCount: 410,
    availability: "in_stock",
    category: "Footwear",
    subcategory: "Sneakers",
    colors: ["White"],
    sizes: ["5", "6", "7", "8", "9"],
    material: "Genuine Nappa Leather",
    pattern: "Solid",
    fit: "Regular",
    style: "Minimalist",
    occasion: "Casual, Daily, Travel, Weekend",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["Genuine Nappa Leather", "Lightweight EVA Cushioning", "Breathable Mesh Lining"],
    deliveryInformation: "🚚 Prime Express Tomorrow",
    isBestSeller: true,
  },
  {
    id: "loc_wom_foot_03",
    provider: "Local",
    providerProductId: "dev_wom_6003",
    title: "Embellished Gold Kolhapuri Mojari Sandals",
    description: "Handcrafted festive Kolhapuri flats with golden thread embroidery and cushioned leather footbed.",
    brand: "Ghungroo Footwear",
    store: "Ajio",
    merchant: "Ajio",
    imageUrl: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.ajio.com/women-gold-embellished-kolhapuri",
    price: 1499,
    originalPrice: 2199,
    currency: "INR",
    discountPercent: 31,
    discountPercentage: 31,
    priceStatus: "development",
    rating: 4.7,
    reviewCount: 180,
    availability: "in_stock",
    category: "Footwear",
    subcategory: "Jutti",
    colors: ["Gold", "Yellow"],
    sizes: ["5", "6", "7", "8", "9"],
    material: "Genuine Leather & Zari Embroidery",
    pattern: "Embroidered",
    fit: "Regular",
    style: "Traditional",
    occasion: "Weddings / Functions, Festive, Puja, Sangeet",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["Handmade Leather Sole", "Bite-Free Toe Ring", "Zari Handwork"],
    deliveryInformation: "🚚 Delivered in 3 Days",
  },

  // --- ACCESSORIES (MEN & WOMEN) ---
  {
    id: "loc_acc_01",
    provider: "Local",
    providerProductId: "dev_acc_1001",
    title: "Minimalist Automatic Watch with Black Leather Strap",
    description: "Sapphire crystal automatic watch with 40mm stainless steel case and genuine Italian black leather strap.",
    brand: "Chronos Atelier",
    store: "Tata CLiQ",
    merchant: "Tata CLiQ",
    imageUrl: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.tatacliq.com/chronos-automatic-watch",
    price: 3499,
    originalPrice: 4999,
    currency: "INR",
    discountPercent: 30,
    discountPercentage: 30,
    priceStatus: "development",
    rating: 4.9,
    reviewCount: 290,
    availability: "in_stock",
    category: "Accessories",
    subcategory: "Watch",
    colors: ["Black", "Silver"],
    sizes: ["One Size"],
    material: "316L Stainless Steel & Genuine Leather",
    pattern: "Solid",
    fit: "Regular",
    style: "Minimalist",
    occasion: "Office, Formal Gala, Daily, Meeting",
    season: "All-Season",
    gender: "Unisex",
    source: "local",
    features: ["Sapphire Crystal Glass", "5 ATM Water Resistant", "Japanese Automatic Movement"],
    deliveryInformation: "🚚 Free Insured Shipping",
    isBestSeller: true,
  },
  {
    id: "loc_acc_02",
    provider: "Local",
    providerProductId: "dev_acc_1002",
    title: "Structured Cognac Pebbled Leather Daily Tote Bag",
    description: "Spacious everyday tote bag crafted in rich pebbled Italian leather with padded laptop compartment.",
    brand: "Cuoio Leather",
    store: "Myntra",
    merchant: "Myntra",
    imageUrl: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80",
    productUrl: "https://www.myntra.com/bags/cognac-pebbled-leather-tote",
    price: 2799,
    originalPrice: 3999,
    currency: "INR",
    discountPercent: 30,
    discountPercentage: 30,
    priceStatus: "development",
    rating: 4.8,
    reviewCount: 310,
    availability: "in_stock",
    category: "Accessories",
    subcategory: "Bag",
    colors: ["Brown", "Tan"],
    sizes: ["One Size"],
    material: "100% Pebbled Full-Grain Leather",
    pattern: "Solid",
    fit: "Regular",
    style: "Smart Casual",
    occasion: "Office, Travel, Daily, Brunch",
    season: "All-Season",
    gender: "Women",
    source: "local",
    features: ["Fits 14\" Laptop", "Reinforced Shoulder Straps", "Interior Zip Pockets"],
    deliveryInformation: "🚚 Delivered in 2 Days",
    isBestSeller: true,
  },
];

export class LocalCatalogProvider implements IMarketplaceProvider {
  public readonly name: MarketplaceProviderName = "Local";
  public readonly status: MarketplaceProviderHealthStatus = "ACTIVE";

  public isConfigured(): boolean {
    return true;
  }

  public getStatus(): MarketplaceProviderStatus {
    return {
      provider: "Local",
      isConfigured: true,
      isConnected: true,
      status: "ACTIVE",
      message: `Curated local fashion catalog active with ${LOCAL_MARKETPLACE_CATALOG.length} verified products across Men's and Women's collections`,
      lastChecked: new Date().toISOString(),
    };
  }

  public async testConnection(): Promise<MarketplaceProviderTestResult> {
    return {
      provider: "Local",
      passed: true,
      status: "ACTIVE",
      latencyMs: 1,
      statusCode: 200,
      productCount: LOCAL_MARKETPLACE_CATALOG.length,
      sampleProduct: {
        id: LOCAL_MARKETPLACE_CATALOG[0].id,
        title: LOCAL_MARKETPLACE_CATALOG[0].title,
        price: LOCAL_MARKETPLACE_CATALOG[0].price,
        imageUrl: LOCAL_MARKETPLACE_CATALOG[0].imageUrl,
        productUrl: LOCAL_MARKETPLACE_CATALOG[0].productUrl,
      },
    };
  }

  public async searchProducts(
    query: FashionParsedQuery,
    filters?: MarketplaceSearchFilters
  ): Promise<MarketplaceProduct[]> {
    const rawQ = query.rawQuery.toLowerCase().trim();
    const targetCat = (filters?.selectedCategory || query.category || "").toLowerCase();
    const targetSub = (filters?.selectedStyles?.[0] || query.subcategory || query.style || "").toLowerCase();
    const targetColor = (filters?.selectedColors?.[0] || query.color || "").toLowerCase();
    const targetFit = (filters?.selectedFits?.[0] || query.fit || "").toLowerCase();
    const effectiveGender = filters?.gender || query.gender;
    const maxBudget = filters?.maxPrice || query.budget?.max;
    const minBudget = filters?.minPrice || query.budget?.min;
    const minRating = filters?.minRating;

    return LOCAL_MARKETPLACE_CATALOG.filter((p) => {
      const titleLower = p.title.toLowerCase();
      const catLower = (p.category || "").toLowerCase();
      const subLower = (p.subcategory || "").toLowerCase();
      const descLower = (p.description || "").toLowerCase();
      const styleLower = (p.style || "").toLowerCase();
      const fitLower = (p.fit || "").toLowerCase();
      const pColors = (p.colors || []).map((c) => c.toLowerCase());

      // 1. Gender Filter: Strictly isolate Men vs Women when specified
      if (effectiveGender && effectiveGender !== "All") {
        if (p.gender !== "Unisex" && p.gender !== effectiveGender) {
          return false;
        }
      }

      // 2. Budget Constraints
      if (maxBudget !== undefined && p.price > maxBudget) return false;
      if (minBudget !== undefined && p.price < minBudget) return false;

      // 3. Rating Filter
      if (minRating !== undefined && p.rating && p.rating < minRating) return false;

      // 4. Fit Filter
      if (targetFit && targetFit !== "all" && targetFit !== "regular") {
        if (fitLower !== targetFit && !titleLower.includes(targetFit)) {
          // Soft check: allow if it's the only criterion or keep exact
        }
      }

      // 5. Category Match
      if (targetCat && targetCat !== "all") {
        if (targetCat === "ethnic wear" || targetCat === "traditional") {
          const isEthnic =
            catLower.includes("ethnic") ||
            titleLower.includes("kurta") ||
            titleLower.includes("kurti") ||
            titleLower.includes("saree") ||
            titleLower.includes("lehenga") ||
            titleLower.includes("nehru") ||
            titleLower.includes("sherwani") ||
            titleLower.includes("anarkali");
          if (!isEthnic) return false;
        } else if (targetCat === "dresses") {
          const isDress =
            catLower.includes("dress") ||
            titleLower.includes("dress") ||
            titleLower.includes("gown") ||
            titleLower.includes("maxi") ||
            titleLower.includes("sundress");
          if (!isDress) return false;
        } else if (targetCat === "tops") {
          const isTop =
            catLower.includes("top") ||
            titleLower.includes("shirt") ||
            titleLower.includes("tee") ||
            titleLower.includes("t-shirt") ||
            titleLower.includes("polo") ||
            titleLower.includes("blouse") ||
            titleLower.includes("hoodie") ||
            titleLower.includes("sweater");
          if (!isTop) return false;
        } else if (targetCat === "bottoms") {
          const isBottom =
            catLower.includes("bottom") ||
            titleLower.includes("jean") ||
            titleLower.includes("pant") ||
            titleLower.includes("trouser") ||
            titleLower.includes("chino") ||
            titleLower.includes("cargo") ||
            titleLower.includes("skirt");
          if (!isBottom) return false;
        } else if (targetCat === "outerwear") {
          const isOuter =
            catLower.includes("outerwear") ||
            titleLower.includes("blazer") ||
            titleLower.includes("jacket") ||
            titleLower.includes("coat") ||
            titleLower.includes("trench");
          if (!isOuter) return false;
        } else if (targetCat === "footwear") {
          const isFoot =
            catLower.includes("footwear") ||
            titleLower.includes("shoe") ||
            titleLower.includes("sneaker") ||
            titleLower.includes("loafer") ||
            titleLower.includes("sandal") ||
            titleLower.includes("jutti") ||
            titleLower.includes("heel");
          if (!isFoot) return false;
        } else if (targetCat === "accessories") {
          const isAcc =
            catLower.includes("accessories") ||
            titleLower.includes("watch") ||
            titleLower.includes("bag") ||
            titleLower.includes("belt");
          if (!isAcc) return false;
        }
      }

      // 6. Color Match
      if (targetColor) {
        const matchesColor =
          pColors.some((c) => c.includes(targetColor) || targetColor.includes(c)) ||
          titleLower.includes(targetColor);
        if (!matchesColor) {
          // Check for explicit conflicting color
          const conflicting = ["red", "white", "black", "blue", "green", "pink", "yellow", "navy", "grey", "tan"].filter(
            (c) => c !== targetColor
          );
          if (conflicting.some((cc) => titleLower.includes(` ${cc} `) || titleLower.startsWith(`${cc} `))) {
            return false;
          }
        }
      }

      // 7. Subcategory / Specific Style
      if (targetSub) {
        const matchesSub =
          subLower.includes(targetSub) ||
          titleLower.includes(targetSub) ||
          descLower.includes(targetSub) ||
          styleLower.includes(targetSub);
        if (!matchesSub && targetCat) {
          // If category matched, allow broad subcategories
        }
      }

      // 8. Keyword fallback
      if (!targetCat && !targetColor && rawQ && rawQ !== "all" && rawQ !== "clothing" && rawQ !== "fashion") {
        const matchesKeyword =
          titleLower.includes(rawQ) ||
          catLower.includes(rawQ) ||
          subLower.includes(rawQ) ||
          descLower.includes(rawQ) ||
          styleLower.includes(rawQ);
        if (!matchesKeyword) return false;
      }

      return true;
    });
  }

  public async getProduct(id: string): Promise<MarketplaceProduct | null> {
    return LOCAL_MARKETPLACE_CATALOG.find((p) => p.id === id) || null;
  }

  public async getCategories(): Promise<string[]> {
    return Array.from(new Set(LOCAL_MARKETPLACE_CATALOG.map((p) => p.category)));
  }

  public generateAffiliateUrl(product: MarketplaceProduct): string {
    return product.productUrl;
  }
}

export const localCatalogProvider = new LocalCatalogProvider();
